header with basket option
miamtech/miam-sample-uikit-integration pull request #30
Opened 2023-11-03 07:32 UTC by walerowicz-miam

replace basket item by shelve item
create header on shelve item
link basket button to old basket view (push on navigation controller)
calculate dynamically basket total amount

2023-11-03 07:33 UTC, walerowicz-miam commented
Current dependencies on/for this PR:
* local-spm
  * **PR #30** <a href="https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/30" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/30?utm_source=stack-comment).

2023-11-06 08:37 UTC, diarmuidmcg requested changes

2023-11-06 08:37 UTC, diarmuidmcg commented on SampleMiamUIKitIntegration/GeneralViews/ViewWithHeaderVIewController.swift
> +
remove whitespace (Alexis is very particular on this)

2023-11-06 08:37 UTC, diarmuidmcg commented on SampleMiamUIKitIntegration/GeneralViews/ViewWithHeaderVIewController.swift
> +                    strongSelf.totalAmountLabel.text = "\(total) €"
if you import MiamIOSFramework, you can use our Double.currencyFormatted() function. This will then use localization to determine the currency (& if it is left or right side)

it can be `total.currencyFormatted()`

2023-11-06 08:37 UTC, diarmuidmcg commented on SampleMiamUIKitIntegration/GeneralViews/ViewWithHeaderVIewController.swift
> +import SwiftUI
do we need these 2 imports?

2023-11-07 08:55 UTC, merged

2023-11-07 08:56 UTC, diarmuidmcg commented
closed by #34 merge