remove navigation bar on tab bar items
miamtech/miam-sample-uikit-integration pull request #33
Opened 2023-11-06 07:32 UTC by walerowicz-miam

2023-11-06 07:32 UTC, walerowicz-miam commented
Current dependencies on/for this PR:
* local-spm
  * **PR #30** <a href="https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/30" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #31** <a href="https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/31" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #32** <a href="https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/32" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #33** <a href="https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/33" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/miamtech/miam-sample-uikit-integration/33?utm_source=stack-comment).

2023-11-06 08:42 UTC, diarmuidmcg requested changes

2023-11-06 08:42 UTC, diarmuidmcg commented on SampleMiamUIKitIntegration/GeneralViews/ViewWithHeaderViewController.swift
> +            }
since `            if vc.viewControllers.count > 1 {
                leftButton.setImage(UIImage(systemName: "chevron.left"), for: .normal)
            }else{
                leftButton.setImage(UIImage(systemName: "line.3.horizontal"), for: .normal)
            }`
 is duplicated, could you create small func that does this (pass in count, etc)?

2023-11-07 08:55 UTC, closed without merging

2023-11-07 08:55 UTC, diarmuidmcg commented
closed by #34 merge